apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS
  region: us-east-1

#privateCluster:
#  enabled: true

vpc:
  id: "vpc-0a4e2cafbeaf3844c"
  subnets:
    public:
      us-east-1a: {id: "subnet-075810487f2b08db2"}
      us-east-1b: {id: "subnet-00c84d7082f8efcf3"}
      us-east-1c: {id: "subnet-0f1e5c0344ed822ed"}
      us-east-1d: {id: "subnet-066a96caaa2d8f837"}
    private:
      us-east-1a: {id: "subnet-0fd5fb4efd0a8c9bd"}
      us-east-1b: {id: "subnet-0867f121f62cc38be"}
      us-east-1c: {id: "subnet-0a9fcf3b27422006f"}
      us-east-1d: {id: "subnet-083ab63989c45b06a"}

managedNodeGroups:
  - name: EKS01-Node
    instanceType: t2.small
    minSize: 2
    maxSize: 10
    desiredCapacity: 3
    privateNetworking: true
    securityGroups:
      attachIDs: ["sg-088d61df3b10f2a4b"]
    ssh: # use existing EC2 key
      publicKeyName: eks-key
  - name: EKS-Bastion
    instanceType: t2.small
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    privateNetworking: false
    securityGroups:
      attachIDs: ["sg-037aaedd274eb1d83"]
    subnets:
      - us-east-1a
    ssh:
      publicKeyName: bastion