---
apiVersion: v1
kind: Namespace
metadata:
  name: gogs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gogs
  name: deployment-gogs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gogs
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gogs
    spec:
      containers:
      - image: gogs/gogs
        imagePullPolicy: Always
        name: gogs
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: gogs
  name: service-gogs
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: gogs
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: gogs
  name: ingress-gogs
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: service-gogs
              servicePort: 80